name: ibo-desktop-app
version: '1.0'
summary: Flutter Demo Counter Application
description: A demo of Counter Application using Flutter
confinement: strict
base: core18
grade: stable
icon: snap/gui/icon.png


apps:
  counter:
    command: ibo-desktop-app
    extensions: [flutter-master]
    plugs:
      - network
      - desktop

parts:
  counter:
    source: https://github.com/shanky367/ibo_desktop_app.git
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application